coordinates:
- 54.560556
- 57.974766
description: '

  Отметка высоты находится на полянке на плато, поросшем хвойным лесом

  '
height: 1165
images:
- comment: Вид на хр. Нары и г. Ямантау с курумника на востоке от вершины
  filename: c17230938fb5bb944dc3a45edfd0983593e8fcf6.jpeg
interpretation: null
name: null
name_alt: Плато
