coordinates:
- 54.44929
- 58.371594
description: Скальный выход
height: 1224
images:
- comment: Вершина (на переднем плане)
  filename: eb19367f4874f1732621d33af865c2ac12f42867.jpeg
interpretation: От русского имени Харитон
name: Харитонова
name_alt: null
