coordinates:
- 54.835335
- 58.861335
description: Узкий курумный гребень
height: 1194
images:
- comment: Вершина
  image: 227c065d75b774deadb145ebb04cd2e83a379e86.jpeg
- comment: Вершина
  image: dea1e220f1d5669b0076147c69c10985d06c72b7.jpeg
interpretation: null
name: null
name_alt: null
