coordinates:
- 54.103886
- 58.427632
description: "Курум в лесу\r\n"
height: 1017
images: []
interpretation: В отличие от относительно невысоких сопок, окружающих гору, на её
  склонах есть небольшие каменные россыпи
name: Рассыпная
name_alt: null
