coordinates:
- 54.539209
- 58.759233
description: "\r\n\r\n"
height: 1065
images:
- comment: Вершина
  filename: d84730ca27c4d37f46cea4db59144f507a1933ac.jpeg
- comment: Вершина (на переднем плане)
  filename: 231b1ceb26872efff8ad1db99c4df7fecd3d30a3.jpeg
interpretation: Похожа на сундук
name: null
name_alt: Сундук, Сундуки
