coordinates:
- 54.319959
- 58.315267
description: "Курумы, хвойное редколесье\r\n"
height: 1328
images:
- comment: Вершина слева, справа - Колокольня
  image: 53836fc3623ee8b0e08b62ae1d8827df28f31f28.jpeg
- comment: Вид с вершины
  image: 3fea3633b47293bdc2a19b5162ae4abd3787458b.jpeg
interpretation: null
name: null
name_alt: null
