coordinates:
- 54.578975
- 57.937778
description: Лес, скальный выход.
height: 1044
images:
- comment: На вершине
  image: 93348a9660f27e9d74ab16b7589f9f9555327129.jpeg
interpretation: Служит ориентиром, открывается вид на окружающую местность.
name: Маяк
name_alt: null
