coordinates:
- 54.549567
- 58.974609
description: Небольшой курумный купол
height: 1120
images:
- comment: Вершина с 1345 (Иремель)
  image: 4bd9f2be3b6c4ae0fe1855cc52982bd150f52a31.jpeg
- comment: Неподалеку от вершины
  image: 67b5e3d72adfdfbbf93cc76964a88ffcbcc32822.jpeg
- comment: Вершина
  image: f9d1c7eea0b10c2551c5e6ab3908f8c9b9a70105.jpeg
interpretation: "<strong>Шыршыл</strong>, <strong>шершил</strong> (баш.) &mdash; еловая,\
  \ <strong>бийик</strong>, <strong>бейек</strong> (баш.) &mdash; высотка, возвышенность.\r\
  \n"
name: Малый Шаршалыбиик
name_alt: null
