coordinates:
- 53.451627
- 58.437199
description: Скальный гребень вулканических пород на альпийском луге
height: 1118
images:
- comment: Вершина Караташ
  image: 203c2064e353800b5a1899da7d31150a29c26f5e.jpeg
- comment: На вершине Караташ
  image: 093e34531e424adda4513e93a6791acd3a6082d5.jpeg
interpretation: Дословно с башкирского &mdash; черный камень (<b>кара</b> &mdash;
  черный, <b>таш</b> &mdash; камень). Но т.к. в тюрских языках слово &laquo;кара&raquo;
  имеет несколько значений, то в данном смысле - безлесая, скалистая гора.
name: Караташ
name_alt: null
