coordinates:
- 54.455205
- 57.849969
description: Лесистая пологая вершина (на восток более крутой сброс)
height: 1017
images:
- comment: Вершина (Вид с Сухих гор 1030)
  image: f11dd0c3e36ba196adf5f1cdb9bf882b3b62b6fe.jpeg
interpretation: null
name: null
name_alt: null
