coordinates:
- 54.502258
- 57.879579
description: ''
height: 1030
images:
- comment: Вид на хр. Нары и г. Ямантау с останцев на юге от вершины
  filename: 3cd54dacb51a1dfeb6909498528b7e71f0890459.jpeg
interpretation: null
name: null
name_alt: null
