coordinates:
- 53.590814
- 58.494697
description: null
height: 1087
images:
- comment: Вершина
  filename: 363fc6fa1056f6bd61197c308935e8ba186a68cd.jpeg
- comment: Вершинный тур
  filename: 91085d483aa5fcd64002a31e7e880b97e223490f.jpeg
interpretation: "<p><b>Шыршил</b>, <b>шершил</b> (баш.) &mdash; еловая, <b>тау</b>\
  \ (баш.) &mdash; гора. <b>Таш</b> (баш.) &mdash; камень.</b></p>\r\n<p><b>Салаватские\
  \ Камни</b> &mdash; в честь народного героя Салавата Юлаева или просто от башкирского\
  \ имени.</p>"
name: null
name_alt: Средний Салават, Салаватские Камни, Шершилтау
