coordinates:
- 54.397704
- 58.235833
description: null
height: 1191
images: []
interpretation: <strong>Веселая</strong> - в смысле радующая глаз стройным пихтовым
  лесом относительно унылого вида лежащего рядом верхового болота.
name: Веселая
name_alt: null
