coordinates:
- 54.823091
- 58.849082
description: null
height: 1128
images:
- comment: Вершина
  filename: 9d2c5f5d288a4c69e41511446b07a21191b9f93a.jpeg
interpretation: null
name: null
name_alt: null
