coordinates:
- 54.500502
- 58.650093
description: Светлые скалы. С восточной стороны - мощный скальный обрыв
height: 1078
images:
- comment: На вершине. Вид в сторону северной части хребта
  filename: e1cba228b691a73d00d95f97907c842bf00a42a6.jpeg
interpretation: ''
name: Белые Гребни
name_alt: null
