coordinates:
- 54.459013
- 58.826766
description: "Скальный выход на курумном куполе\r\n"
height: 1205
images:
- comment: Вершина
  image: dd4d434e446114300f178b4d2e42894bff8b331f.jpeg
- comment: Вершина с 1233 (Иремель)
  image: ad4b23cbb5e14efbdbd03c00b17e4e719d1332fa.jpeg
interpretation: "<ol>\r\n<li><strong>Аулак</strong> (баш.) &mdash; безлюдный, глухой\r\
  \n<li><strong>Аулак</strong> (тюрк.) &mdash; место изобилующее дичью\r\n</ol>"
name: Большой Аваляк
name_alt: null
