coordinates:
- 55.004411
- 59.486027
description: Отдельно стоящие скалы-останцы.
height: 1067
images:
- comment: С Севера
  filename: 1047269004e6de1649cd51cfc6d94ff7fdd46dac.jpeg
- comment: Вершина
  filename: 66aec0eaa8e192a5d189c4ddb3b2379c3d25549b.jpeg
- comment: Вершина
  filename: 635dc200ab6d4465061bd16c93157075515bf522.jpeg
interpretation: <b>Сопка</b> &mdash; гора с округлой вершиной. Последняя из трех сопок
  части хребта Уреньга, лежащей недалеко от Златоуста.
name: Два Брата
name_alt: Третья Сопка
