coordinates:
- 54.248442
- 58.349582
description: Некрутой скальный гребень, поросший ёлками. Чуть ниже по склону к востоку
  - скальная стена. В километре севернее - цепь скальных останцев, по которым и назван
  хребет.
height: 1161
images:
- comment: Вершина (с цирка)
  image: ffa42173bd42c50a954ec3b9b344aa684b0770a1.jpeg
interpretation: "<b>Ялангас</b> (баш.) &mdash; открытый, голый.\r\n"
name: null
name_alt: Малый Ялангас
