coordinates:
- 54.113646
- 58.619459
description: 'По названию реки Мазара


  '
height: 1008
images:
- comment: На вершине
  image: 20328de25cf3ede646e2e564c31ae1a454f34f23.jpeg
interpretation: null
name: null
name_alt: Мазара
