coordinates:
- 53.700522
- 57.639331
description: Лесостепь,  два небольших скальных выхода, сложенных сланцевыми породами.
height: 1271
images:
- comment: Вершина
  image: a2941cb7a4645a65b905987f723422c930bfd4e3.jpeg
- comment: Вид с вершины на север
  image: d91083a8355470eba1f19e5edd350e3d9371e466.jpeg
- comment: Вершинная палочка
  image: 348e4f0405ec15cb693087eb14c2883ef6df5c93.jpeg
interpretation: "<p><b>Бишитэк</b>, <b>бишэтэк</b> (баш.)  &mdash; пять подолов, оборок.\
  \ пять склонов, подъемов.</p>\r\n<p><b>Биш</b>, <b>беш</b> &mdash; пять. <b>Итэк</b>,\
  \ <b>этэк</b> &mdash; подол, оборка. Подошва горы, склон. Тау (баш.) &mdash; гора.\r\
  \n\r\n<ol>\r\n<li>Пять основных вершин хребта Шатак</li>\r\n<li>Вершина имеет пять\
  \ подолов (подъёмов), пять ступеней на пути к вершине.</li>\r\n<li>Скалы вершин,\
  \ сложенные сланцами пласт к пласту, и есть пять оборок, пять подолов (пять - метафорическая\
  \ цифра).</li>\r\n</ol>\r\n"
name: Большой Шатак
name_alt: Бишитэк, Биш-Тау
