coordinates:
- 54.793016
- 58.798141
description: null
height: 1011
images:
- comment: Вершина
  filename: 757b5e34c806f4daf2acec875629b91109b101a0.jpeg
interpretation: null
name: null
name_alt: null
