coordinates:
- 54.528964
- 57.923864
description: Две скалы. Оригинальный ракурс на Ямантау, основание которой заслонено
  вершиной хребта Нары &mdash; горой <a href="/summit/133">Кашкатура</a>.
height: 1065
images:
- comment: На вершине
  image: 4187603004594b460487622ed3c34b7324d3ffb5.jpeg
- comment: Под вершиной
  image: 29302ec5b139a6d545cae64f56ac968724ad67f2.jpeg
interpretation: Цвет скал на вершине похож на красную глину. Издали скалы похожи на
  слепленных из глины болванов.
name: Глинка
name_alt: null
