coordinates:
- 54.360808
- 58.425236
description: "Скальный гребешок, курумы.\r\n"
height: 1141
images:
- comment: Вершина (с Верхнеаршинска)
  image: 682682b28576d5b655149ecc713694aa424414fe.jpeg
- comment: На вершине
  image: 47cbca379c82492ecb1707cd0134fafd31e8eafe.jpeg
interpretation: "<ol>\r\n<li><strong>Кюмэр</strong> (баш.) &mdash; горбатый, <strong>зэк</strong>\
  \ (баш.) &mdash; гора.\r\n<li><strong>Кюмэр</strong> (баш.) &mdash; горбатый, <strong>дак</strong>\
  \ (баш.) &mdash; имяобразующий аффикс.\r\n</ol>"
name: Малый Кумардак
name_alt: null
