coordinates:
- 54.559846
- 58.877219
description: "Горнотундровое плато, скальный выход\r\n"
height: 1406
images:
- comment: Вид с Малого Иремеля
  image: c79a90e17641e300a8a0acd886a7c668a0e96884.jpeg
- comment: С хребта Ягодного
  image: 4945df7bc3b81bcd695bf852e867cf537026304a.jpeg
interpretation: ''
name: null
name_alt: null
