coordinates:
- 54.449211
- 58.136651
description: 'По форме похожа на копну,стожок


  '
height: 1280
images:
- comment: Вид с вершины
  filename: ce79c0561ecdc45558c0ec2da7cf3115fb2078c8.jpeg
- comment: Вид с вершины 2
  filename: 2d1efb7b904748f40c0ab5b2fb16b9fa680487f4.jpeg
interpretation: null
name: Копешка
name_alt: null
