coordinates:
- 54.198636
- 58.481758
description: Скалы-останцы. На западном склоне горы &mdash; скалы-останцы &mdash;
  Большие и Малые Столбищи.
height: 1026
images:
- comment: Вершина
  image: 8bf0caeaf3c17df3d658dce17c6f8339c2f09ed8.jpeg
interpretation: null
name: Столбы
name_alt: null
