coordinates:
- 54.27593
- 58.210549
description: Относительно пологий курумный купол, на вершине - скальный выход.
height: 1383
images:
- comment: Вершина
  image: e3deda00f09cd864c1fe4fa67cabb94ef6166dbf.jpeg
- comment: Вершинный тур
  image: d0d0350c38535491b8c9d0e8d4bb3ab49f4d7283.jpeg
interpretation: "<strong>Угловой</strong> &mdash; по расположению на хребте. Достоверного\
  \ объяснения слова \"машак\" не существует. Версии:\r\n<ol>\r\n<li><strong>Башак</strong>,\
  \ <strong>машак</strong> (баш.) &mdash; колос</li>\r\n<li><strong>Ук башагы</strong>\
  \ (баш.) &mdash; наконечник стрелы</li>\r\n</ol>"
name: Угловой Машак
name_alt: null
