coordinates:
- 54.559088
- 58.847257
description: Скалы-останцы.
height: 1393
images:
- comment: Вид на вершину с Жеребчика
  filename: 5286dd9cfde150116bd9e4528516603c29277868.jpeg
interpretation: <strong>Сукташ</strong> (баш.) &mdash; «торчащий островерхий камень».
  <strong>Сундуки</strong> &mdash; по форме (вершина представляет собой череду скал,
  сложенных &laquo;квадратными&raquo; по форме глыбами).
name: Сукташ
name_alt: Суктаж, Сундуки, Сукташ-Сундуки
