coordinates:
- 53.658618
- 58.537077
description: "Лесостепь, камни\r\n"
height: 1036
images:
- comment: Вершина
  image: e797788c5b34655477fd51c68ac3842c0845341e.jpeg
interpretation: null
name: null
name_alt: Северная Кусимовка
