coordinates:
- 54.194598
- 58.019654
description: Западнее находится еще одна вершинка. на которой установлен геодезический
  репер, но она несколько ниже.
height: 1052
images: []
interpretation: null
name: null
name_alt: null
