coordinates:
- 54.516433
- 57.969234
description: Крутая каменная россыпь на склоне, обращённом в долину р. Тюльмень. Скальный
  выход на гребне, курумная россыпь на склоне очень круто обрывающемся в долину Тюльменя.
  Замечательный вид на Шелома, Нары, долину Тюльменя.
height: 1062
images:
- comment: Вид с Россыпной в сторону хребта Нары и г. Ямантау
  filename: f81a7322b8fff39cf119d36b565396c4dc50b333.jpeg
- comment: Россыпная (на переднем плане). Вид с г. Глинка
  filename: d2241342fb134e807566651a69c450cfd7135206.jpeg
interpretation: null
name: Россыпная
name_alt: null
