coordinates:
- 54.159218
- 58.205223
description: Скалы среди курумов
height: 1088
images:
- comment: Вершина
  image: 1aad0c28a098013ca0367333ab863d72b4dad44b.jpeg
interpretation: ''
name: null
name_alt: null
