coordinates:
- 53.768825
- 58.093856
description: "Берёзовое редколесье, плато.\r\nИмеются следы от тяжелой техники (заградительные\
  \ работы при пожаре в 2010 г.)\r\n"
height: 1045
images:
- comment: На вершине
  filename: b58ebebb18f2274412bdf69edbfa07a2385335a7.jpeg
interpretation: null
name: null
name_alt: null
