coordinates:
- 54.306637
- 58.293634
description: Большой курумный конус, вытянутый по оси хребта, крутые западный и восточный
  склоны. Перепад высот от границы леса до вершины &mdash; от 250 до 300 метров. Одна
  из самых красивых и крутосклонных вершин Южного Урала. Замечательные панорамы с
  вершины.
height: 1354
images:
- comment: С Ялангаса
  filename: a027e2d5e05062d39e5bb8931f50b64a8a5378bd.jpeg
- comment: С севера
  filename: 3b762f5cfbe7740d8602c5a57a793c190f8edd8f.jpeg
- comment: С северного цирка инзерских зубчаток
  filename: b5cb376ff609d0ae6244533a60c343e7d9c47b30.jpeg
interpretation: Название дано за характерную пирамидальную форму
name: Колокольня
name_alt: null
