coordinates:
- 54.817625
- 58.930331
description: "Большой курумный купол, на вершине - скальный выход\r\n"
height: 1222
images:
- comment: Вид на вершину с г. Малый Уван
  image: 4ecdfaad3c93e1f56f031e63fb7c0af23d619bce.jpeg
interpretation: <b>Уба</b> (баш.) &mdash; холм, курган. Вершина горы - стогообразный
  купол, сплошь покрытый курумами. С перевала Сибирский (на Большой Суке) действительно
  выглядит, как холм или стог.
name: Уван
name_alt: null
