coordinates:
- 54.580634
- 58.569836
description: "\r\n\r\n"
height: 1048
images:
- comment: Вершина на переднем плане (справа)
  filename: 0b22e7109a5bf757ca9e87216be0c95ef9e3b72e.jpeg
interpretation: <b>Пасынок</b> &mdash; неродной. Отрог хребта
name: null
name_alt: Пасынок
