coordinates:
- 54.649035
- 58.65252
description: Большой курумный купол &mdash; &laquo;кабан&raquo;.
height: 1389
images:
- comment: Вершина
  image: 4f04614d329f79db8a7d23bf0fb231ace235bb5b.jpeg
- comment: Вершина
  image: dff6ccdc01c6dcdb9c9bad1197aa2c4158bc52c0.jpeg
interpretation: 'Расположена поперек хребта Зигальга. '
name: Поперечная
name_alt: null
