coordinates:
- 55.315939
- 59.841355
description: Курумный купол
height: 1177
images:
- comment: С юга
  image: e999a23f0453b7ed3685b29eefec84f27498f6d1.jpeg
- comment: Вершина
  image: 3b340c4af706a21af45724ee24d203a121d17c2d.jpeg
- comment: Плато Круглицы
  image: ded862de705ef39c65ddbc403beb43b8d55448bb.jpeg
interpretation: "<p><b>Круглица</b> &mdash; по форме, с юга кажется круглой. Сопка-гора\
  \ с округлой вершиной.</p>\r\n<p><b>Таган</b> (баш.) &mdash; подставка, треножник.\
  \ <b>Ай</b> &mdash; луна. Подставка луны, лунный треножник.\r\n<p><b>Ай</b> (тюрк.)\
  \ &mdash; суффикс с уменьшительно-ласкательным значением. <b>Таганай</b> &mdash;\
  \ треножничек, таганочек</p>"
name: Круглица
name_alt: Круглая Сопка, Круглый Таганай, Башкирская Шапка
