coordinates:
- 54.649947
- 58.98791
description: "Лес, скальный выход\r\n"
height: 1018
images:
- comment: Вершина с 1345 (Иремель)
  filename: 37caf7fe6977cca3c8293ccb58f94e9397d99cb5.jpeg
interpretation: <b>Бейек</b> (баш.) &mdash; высота, высотка, одинокий холм. Равнозначное
  русскому орфографическому термину &laquo;шишка&raquo;.
name: Бияцкая Шишка
name_alt: null
