coordinates:
- 54.377182
- 58.419404
description: "Большой курумный конус, вытянутый по оси хребта/ перепад высот от края\
  \ леса до вершины от 100 до 200м. На вершине скальный гребень.\r\n"
height: 1318
images:
- comment: С Малого Кумардака
  filename: 3c7264c0b5a0e343c2538c5db707e7a5d48d18a3.jpeg
- comment: С Малого Кумардака
  filename: 20b3d84a0cfce3daacd6c22778d2f2418ea92368.jpeg
interpretation: "<ol>\r\n<li><strong>Кюмэр</strong> (баш.) &mdash; горбатый, <strong>зэк</strong>\
  \ (баш.) &mdash; гора.\r\n<li><strong>Кюмэр</strong> (баш.) &mdash; горбатый, <strong>дак</strong>\
  \ (баш.) &mdash; имяобразующий аффикс.\r\n</ol>"
name: Большой Кумардак
name_alt: null
