coordinates:
- 54.127789
- 58.31852
description: "Невысокие скалы\r\n"
height: 1297
images:
- comment: С вершины 1136
  filename: 14c9121cdca463886f393b2fd43f968d730e17ac.jpeg
- comment: С Отнурка
  filename: c67bc7fcc416a89e7bf8ccd2fa8899345406b96a.jpeg
- comment: Вершина (с Журболота)
  filename: aa6b7d6764940dc57221feab95d0c813caa6d11b.jpeg
interpretation: "<strong>Ялангас</strong> (баш.) &mdash; открытый, голый. Открытая,\
  \ голая гора, гора с большой поляной.\r\n"
name: Ялангас
name_alt: ''
