coordinates:
- 54.675238
- 58.683575
description: Невысокий курумный купол овальной формы с плоской вершиной и скальными
  выходами.
height: 1310
images:
- comment: Вершина
  filename: f6d5b828e4f7bf2aaf64d93023ab8cc751626afc.jpeg
- comment: Вершина
  filename: cccd945de89fb94490939373244fa35e1e5adf59.jpeg
interpretation: "<ol>\r\n<li><strong>Евлакта</strong> &mdash; горная речка на хребте\
  \ Зигальга</li>\r\n<li><strong>Ак</strong>,<strong>ах</strong>,<strong>акты</strong>,<strong>ахты</strong>\
  \ (древнебаш.) &mdash; течь,течение,поток,протока\r\n<li><strong>Евлаха</strong>\
  \ &mdash; русское мужское имя,сокращенное от Евлампий (см. &laquo;Уральские сказы&raquo;\
  \ П.П.Бажова, рассказ &laquo;Железковы покрышки&raquo;)</li>\r\n</ol>\r\n"
name: null
name_alt: Евлахта, Евлакта
