coordinates:
- 53.684644
- 58.563401
description: "Лесостепь, камни\r\n"
height: 1027
images:
- comment: Вершина
  image: 1de852a449de7375c66e73032c0150b756bf0386.jpeg
interpretation: null
name: null
name_alt: null
