coordinates:
- 53.769608
- 57.734962
description: "\r\n\r\n"
height: 1011
images:
- comment: Вершина
  image: 989840a3005076a9b7debe37f4d23015d6b88462.jpeg
- comment: Вид с вершины в сторону хребта Крака
  image: 1e33b9debf0b9c7ffc0d1e97ab7e7345cee7d3a1.jpeg
interpretation: <b>Кара</b> (баш.,тюрк.) &mdash; тёмный, чёрный, но в случае употребления
  к горам указывает на безлесость, пустынность. <b>Таш</b>(баш.) &mdash; камень, гора.
  По смыслу можно перевести как &laquo;безлесая вершина с камнями, скалами&raquo;.
name: Караташ
name_alt: null
