coordinates:
- 54.885971
- 59.189165
description: "Лес, небольшой обрывчик на северо-восток\r\n"
height: 1013
images:
- comment: Вершина (справа). Слева - Б. Нургуш
  image: 5a83a8437f1d9688242fa8cb6b742e058920d398.jpeg
- comment: Вершина
  image: 840bf9bc8ef4ec4e7e665211dc106a68d2355c15.jpeg
- comment: Вид с Лукаша в сторону Уреньги
  image: 7bf4fa00a193df8de73093662d0a21b4782c0b86.jpeg
interpretation: Мужское имя <b>Ныкыш</b>, <b>Нугаш</b> (тюрк.) &mdash; упорный, настойчивый.
  Основа <b>нука</b>, <b>нуга</b> и имяобразующий суффикс &mdash; <b>-ш</b>
name: Лукаш
name_alt: Нукаш
