coordinates:
- 54.296437
- 58.104842
description: "\r\n\r\n"
height: 1174
images: []
interpretation: <strong>Шакар</strong> &mdash; распостраненное у мусульман арабское
  имя в значении совершающий славу, благодеяние, хвалу. <strong>Ит</strong>, <strong>эт</strong>
  &mdash; собака
name: Шакитар
name_alt: null
