coordinates:
- 54.73725
- 58.950873
description: Курумы, скальный выход, редколесье.
height: 1197
images:
- comment: Вершина
  image: 369f97cf8d4442e0e7cbed1945d4993a6d17b0f7.jpeg
interpretation: null
name: null
name_alt: null
