coordinates:
- 54.710205
- 59.46569
description: "Курумный купол, скальный выход.\r\n"
height: 1016
images:
- comment: Вид с вершины 1
  filename: e8b148585d00a6fd5c963449c2b0e84f7a745ee3.jpeg
- comment: Вид с вершины 2
  filename: 319a8d7b91c780f961cf9999fb3123739d3d73cc.jpeg
interpretation: "<ol>\r\n<li><b>Круглая</b> &mdash; по форме. <b>Сопка</b> &mdash;\
  \ гора с округлой вершиной. Крулгая гора.</li>\r\n<li><b>Таш</b> (баш.) &mdash;\
  \ камень. Уйский камень &mdash; на восточном склоне берет начало река Уй.</li>\r\
  \n<li><b>Уй</b> (тат.,баш.) &mdash; долина, низина. <b>Тау</b> (баш.) &mdash; гора.\
  \ \r\n<li><b>Кара</b> (баш.,тюрк.) &mdash; тёмный, чёрный, но в случае употребления\
  \ к горам указывает на безлесость, пустынность. <b>Таш</b>(баш.) &mdash; камень,\
  \ гора. По смыслу можно перевести как &laquo;безлесая вершина с камнями, скалами&raquo;.</li>\r\
  \n</ol>"
name: Круглая Сопка
name_alt: Уй-Таш, Уй-Тау, Караташ
