coordinates:
- 54.100004
- 57.905168
description: Курумы, лес, скальные выходы
height: 1109
images: []
interpretation: <b>Кайын</b> (баш.) &mdash; береза. <b>Каен</b> (тат.) &mdash; береза.
  <b>Тюбэ</b> (баш.) &mdash; холм. Березовый холм
name: Каин-Тюбе
name_alt: null
