coordinates:
- 54.532551
- 58.854596
description: ''
height: 1310
images:
- comment: Вид с вершины на Иремель
  image: 6cae6963b77f389b7d16d54aad65289a928da8f9.jpeg
interpretation: null
name: null
name_alt: null
