coordinates:
- 54.536663
- 58.382609
description: "Курумы, невысокие скалы\r\n"
height: 1311
images:
- comment: Вершина
  filename: 694c4c1bd45ec4c91a6c2f031035e84330635319.jpeg
interpretation: <strong>Шелом</strong> &mdash; шлем, холм, бугор.
name: null
name_alt: Третий Шелом
