coordinates:
- 53.825363
- 58.127913
description: Платообразная вершина с редколесьем
height: 1018
images:
- comment: Вершина (с Арвякрязя)
  filename: 4b025fe1cbab3fb0cd6aab23e4b9759f0cc2b266.jpeg
interpretation: null
name: null
name_alt: null
