coordinates:
- 54.567086
- 58.960276
description: Юго-западнее Тюлюкских болот.
height: 1051
images:
- comment: Вершина с р. Тюлюк
  image: 1f3170c31b6dca743d4e1d4d6f55f2016a9b0bfd.jpeg
- comment: Вершина с 1345 (Иремель)
  image: 34edb8833b3cf009a7b2798e842d95a091a3a3e8.jpeg
- comment: Панорама с вершины в сторону Иремеля
  image: b42e21a496c3d8fc6e0810e9e351d7067f2b0846.jpeg
interpretation: null
name: null
name_alt: null
