coordinates:
- 55.364312
- 59.890772
description: Обычно на картах высоту Дальнего Таганая обозначают как 1112, но это
  высота плато, где расположена метеостанция. А высшая точка (1148) находится чуть
  западнее, на гребне.
height: 1148
images:
- comment: Вершина
  image: 96a4f0e6681158d9544fc2f007357ba5de9d3246.jpeg
interpretation: "<p><b>Дальний</b> &mdash; наиболее удаленный от Златоуста.\r\n<p><b>Таган</b>\
  \ (баш.) &mdash; подставка, треножник. <b>Ай</b> &mdash; луна. Подставка луны, лунный\
  \ треножник.\r\n<p><b>Ай</b> (тюрк.) &mdash; суффикс с уменьшительно-ласкательным\
  \ значением. <b>Таганай</b> &mdash; треножничек, таганочек</p>"
name: Дальний Таганай
name_alt: null
