coordinates:
- 54.122268
- 58.064696
description: На вершине - скальный выход
height: 1200
images: []
interpretation: "<ol>\r\n<li><strong>Ер</strong> (тюрк.) &mdash; земля, место, урочище.\
  \ <strong>ик</strong>,<strong>ык</strong> &mdash; подветренная, заветренная сторона.\
  \ Безветренное, укромное место. укрытие, убежище. <strong>Таш</strong> (баш.) &mdash;\
  \ камень</li>\r\n<li><strong>Ерек</strong>(баш.) &mdash; ольха, <strong>таш</strong>(баш.)\
  \ &mdash; камень, гора.</li>\r\n</ol>"
name: Ерикташ
name_alt: null
