coordinates:
- 54.457827
- 58.618936
description: С восточной стороны -  скальный обрыв и курумы
height: 1042
images:
- comment: Вершина
  image: 85517dbc80f73e9fda65df7a53ab02069317265b.jpeg
- comment: Вершина (вид с г. Белые Гребни)
  image: e98ec0280e7c5589a2958b52553144815f9469a6.jpeg
interpretation: null
name: null
name_alt: null
