coordinates:
- 54.142934
- 58.201572
description: "Версии не бесспорные:\r\n<ol>\r\n<li><strong>Зэк</strong> (баш.) &mdash;\
  \ гора</li>\r\n<li><strong>Мэйэрзэк</strong> &mdash; имя башкира</li>\r\n<li><strong>Дак</strong>\
  \ (баш.) &mdash; имя-образующий аффикс</li>\r\n</ol>"
height: 1225
images:
- comment: Вершина
  filename: 843219e4f23d455b08f764f5b1e63ce3e949b030.jpeg
- comment: Вид с вершины
  filename: 63b40fd62e5d594ce9ae2d96e94b01e3e2b91d3a.jpeg
- comment: Вид с вершины 2
  filename: f7862e16aac80280a96d7c624a01da48f0044d3a.jpeg
interpretation: Мощный скальный бастион. Классный вид на Ямантау.
name: Маярдак
name_alt: null
