coordinates:
- 54.565295
- 59.016838
description: Лесистая вершина
height: 1028
images:
- comment: Вид с вершины в сторону Шаршалыбиика
  filename: 5d6c9885d537b8c90ba2959ea1d0733da0665d84.jpeg
- comment: Скальные выхода неподалеку от вершины
  filename: bd9508f88508bbd827eb15a87f0565d96f58b0f1.jpeg
interpretation: <strong>Кук</strong> (баш.) &mdash; синий, сивый, <strong>таш</strong>
  (баш.) &mdash; камень. Синий камень, синяя гора.
name: Кукташ
name_alt: null
