coordinates:
- 54.496564
- 58.902082
description: На вершине &mdash; скальный гребень, отличный вид на Иремель и долины
  Тыгына и Белой
height: 1253
images:
- comment: Вершина с 1233 (Иремель)
  filename: 7f784c0798b0a46c1fffe3bcdbfcdcc52840ed02.jpeg
- comment: Вершина с 1345 (Иремель)
  filename: e029e64ead5de400acdc007c501d595bcfb582d5.jpeg
interpretation: "<ol>\r\n<li><strong>Аулак</strong> (баш.) &mdash; безлюдный, глухой\r\
  \n<li><strong>Аулак</strong> (тюрк.) &mdash; место изобилующее дичью\r\n</ol>"
name: null
name_alt: Средний Аваляк
