coordinates:
- 54.908025
- 58.95892
description: "Курумы, горная тундра, скальный выход\r\n"
height: 1102
images:
- comment: Вершина
  image: 6023e961cd307e1d95efc3192273bf133cada6d5.jpeg
interpretation: <b>Сукы</b> (баш.) &mdash; сопка, пик, островерхие выступы скал на
  вершине горы, гребень. Действительно, некоторые вершины этого хребта - гребневые,
  например, 1139 и 1194.
name: null
name_alt: Малая Сука
