coordinates:
- 54.999362
- 59.479293
description: 'Отдельно стоящие скалы-останцы


  '
height: 1027
images:
- comment: Вершинный тур
  filename: 1d9883cc5c0a496c7753fafc32bba9b0730d9fa1.jpeg
interpretation: null
name: Два Братца
name_alt: Два Братца
