coordinates:
- 53.637561
- 57.597799
description: Скальный гребень, состоящий из огромных каменных плит, расположенных
  наклонно и сложенных сланцевыми породами.
height: 1026
images:
- comment: Вершина
  image: 2af879cc738e9ba42a947a6cff51ba5ce8faa386.jpeg
interpretation: null
name: null
name_alt: null
