coordinates:
- 54.211002
- 58.166669
description: "Курумы, скальный выход\r\n"
height: 1261
images:
- comment: Вершина
  image: 91907ff434009ce7877e320b47c813000a432721.jpeg
interpretation: null
name: Шикташ
name_alt: null
