coordinates:
- 54.819501
- 59.148326
description: Главная (высочайшая) вершина хребта Нургуш. Высшая точка Челябинской
  Области. Cопка-гора с округлой вершиной, горнотундровое плато.
height: 1406
images:
- comment: Вершина
  filename: a0436be66f003c71bd92cca0a7cacf688365c407.jpeg
- comment: Вид на вершину (справа) со Среднего Нургуша (1350)
  filename: 1c6fe8c2c2cc1b52934bc277f1ae79a539c0da95.jpeg
interpretation: "<ol>\r\n<li><strong>Нур</strong> (баш.) &mdash; луч, сияние. <strong>Кош</strong>,\
  \ <strong>гуш</strong>, <strong>куш</strong> (баш.) &mdash; птица. Лучезарная, сияющая\
  \ птица.</li>\r\n<li><strong>Нуру</strong>, <strong>нура</strong> (древний тюрко-монгольский)\
  \ &mdash; хребет, горная цепь, гора. <strong>Кош</strong>, <strong>гуш</strong>,\
  \ <strong>куш</strong> (баш.) &mdash; птица; птичий хребет.</li>\r\n</ol>"
name: null
name_alt: Большой Нургуш, Главная Сопка
