coordinates:
- 54.519924
- 58.842556
description: Огромный курумный купол &mdash; &laquo;кабан&raquo;, на протяжённом горнотундровом
  плато &mdash; скальный выход. Вторая по высоте гора Южного Урала, со всеми вытекающими
  отсюда последствиями.
height: 1582
images:
- comment: Вершина с Аваляка
  image: c220af74704be2dd9f1bcb426ea0a2921c493e0b.jpeg
- comment: Вершина
  image: 0b97341b9da3bb6915e69f180776e095a6a38b8d.jpeg
interpretation: "<p>Из тюркских языков слово &laquo;иремель&raquo; объяснить не удаётся,\
  \ это значит, что слово &laquo;иремель&raquo; &mdash; добашкирского происхождения.\
  \ Наиболее вероятно, что оно происходит из языка финноугорской группы, в частности\
  \ протовенгров, и протоманси, обитавших здесь до прихода башкир.</p>\r\n\r\nДругие\
  \ версии:\r\n<ol>\r\n<li><strong>Ырым</strong> (баш., тат.) &mdash; заклинание,\
  \ колдовство. <strong>Ырымлы</strong> &mdash; заговоренный, заколдованный.</li>\r\
  \n<li><strong>Ир</strong> (тюрк.) - мужчина, герой, муж, <strong>эмэл</strong> (монг.)\
  \ - седло, &laquo;Седло героя&raquo; (толкование проф. А. К. Матвеева).</li>\r\n\
  <li><strong>Кабан</strong> &mdash; так башкиры называли стогообразные, покрытые\
  \ каменными россыпями вершины.</li>\r\n</ol>"
name: Большой Иремель
name_alt: Иремеля, Еремель, Ирэмэл, Эреням, Большой Кабан, Иремельская Сопка
