coordinates:
- 53.579944
- 58.522597
description: 'По расположению на хребте

  лес, поляна

  На вост. склоне, в ущелье Курузяк - скалы Чёртов Палец и Баба.'
height: 1005
images:
- comment: На вершине
  image: f7d4f46b38063922b15ba164f17fb174274e5b9f.jpeg
interpretation: null
name: null
name_alt: Срединная
