coordinates:
- 54.521712
- 58.335328
description: <p>Огромный курумный купол, вытянутый по оси хребта. Перепад высот от
  края леса до вершины &mdash; 250-500 метров. Высшая точка &mdash; скальный выход.</p>
height: 1427
images:
- comment: Вершина
  filename: db79b21924d1b19fd3333fd10e1ca17fcc6391b1.jpeg
- comment: Вид с хребта Бакты
  filename: 947041a801d727f717bb40dfa977ccabbb80bdce.jpeg
interpretation: <strong>Шелом</strong> &mdash; шлем, холм, бугор.
name: Большой Шелом
name_alt: Большой Шолом
