coordinates:
- 54.353268
- 57.944164
description: Труднодоступная скала. Севернее, на плато 1229м &mdash; урочище Дворики
  (скальный город)
height: 1340
images:
- comment: Вид с вершины
  filename: a90218d1e66aec9a2ed6cb9f36725c511772c360.jpeg
- comment: Вид с вершины 2
  filename: 2f960af8250373c1c2031eb69ba1a8d56671a24f.jpeg
- comment: Вид с вершины 3
  filename: c608cafb5154cac76241604ba7ddee142a200e86.jpeg
interpretation: "<p><b>Кашка</b> (тюрк.) &mdash; лысый.</p>\r\n<p><b>Кашга</b> (древнетюрк.)\
  \ &mdash; белое пятно на лбу животного, в географии &mdash; голое, не заросшее растительностью\
  \ место, голец в горах.</p>\r\n<p><b>Тура</b> (тюрк., монг., южная сибирь) &mdash;\
  \ город, поселение, жилище на возвышенности.</p>\r\n<p><b>Тура</b> (древнетюрк.)\
  \ &mdash; укрепленное жилище, крепость. </p><p><b>Тора</b> (баш) &mdash; висячий.</p>\r\
  \n<p><b>Тура</b> &mdash; камни, похожие формой на человека или на какое-нибудь животное</p>\r\
  \n<p><b>Тюбе</b>, <b>тюбэ</b> (баш.) &mdash; холм, высотка, возвышенность."
name: Кашкатура
name_alt: Кашкатюбе
