coordinates:
- 53.657123
- 57.614942
description: "Группа скальных останцев\r\n"
height: 1099
images:
- comment: Вершина
  filename: c66e8e23279074f119770b1166780c4060e7615c.jpeg
- comment: Сложенные из круглых камней скалы
  filename: dec79f04ecc8b651ad452aa99a2ea5e57fe47c88.jpeg
interpretation: <b>Капка</b> (баш.) &mdash; ворота. <b>Таш</b> (баш.) &mdash; камень.
  Скала рядом с горным проходом. Конкретное название можно объяснить как скала рядом
  со звериной тропой из долины Кухтура на плато хребта.
name: Капкаташ
name_alt: null
