coordinates:
- 53.678651
- 57.614887
description: Лесостепь. Рядом - урочище Кужак.
height: 1206
images:
- comment: Панорама с вершины
  filename: 8a3ce2618869c4c7f3e96c4598708af77a31d925.jpeg
interpretation: null
name: null
name_alt: Плато Шатака
