coordinates:
- 54.280198
- 57.850794
description: Высокий протяжённый скальный гребень
height: 1251
images:
- comment: Вершина
  filename: 8d2c1685bae27996414d36bb6edce2b63b25e3ea.jpeg
- comment: Вид с вершины
  filename: 7db368a32d2b14a8df25d9f5d912cc1598839e3b.jpeg
- comment: Вид с вершины 2
  filename: 47b7d69fa121aafb6304260b036784f792d6f8fe.jpeg
interpretation: null
name: null
name_alt: null
