coordinates:
- 53.709764
- 58.582732
description: Три скальных гребня вулканических пород
height: 1048
images:
- comment: Вершина
  filename: 1ae1757052c275714b4b2925d58f835d97f55cce.jpeg
interpretation: "<strong>Куш</strong> (баш.) &mdash; двойной, парный, соединенный.\
  \ <strong>Ай</strong>  (баш.) &mdash; уменьшительно-ласкательный суффикс. Вместе\
  \ с соседней вершиной, горой <a href=\"/summit/77\">Бабай</a>, составляют пару.\r\
  \n"
name: Кушай
name_alt: null
