coordinates:
- 54.514906
- 57.899755
description: "Лесистая\r\n"
height: 1069
images:
- comment: Вершина 1069. Вид с г. Глинка
  filename: 1963820021e0577071762e47f3f7d85eda73b2e5.jpeg
interpretation: null
name: null
name_alt: null
