coordinates:
- 54.553034
- 58.897172
description: Тундровое плато Малого Иремеля, пожалуй, самое большое на Южном Урале.
height: 1449
images:
- comment: Вершина
  filename: 2f4506557b947d94d8ae90d2f46420f28ab3fb23.jpeg
- comment: Вершина с 1345 (Иремель)
  filename: 39c71226c82e1718fa799132be87495362f50161.jpeg
interpretation: "<ol>\r\n<li><strong>Иремель</strong> (баш.) &mdash; священная гора.</li>\r\
  \n<li><strong>Ырым</strong> (баш., тат.) &mdash; заклинание, колдовство. <strong>Ырымлы</strong>\
  \ &mdash; заговоренный, заколдованный.</li>\r\n<li><strong>Ир</strong>,<strong>из</strong>,\
  \ <strong>эйэр</strong> (тюрк.) &mdash; седло, <strong>эмэл</strong> (монг.) &mdash;\
  \ седло, седловина (название по форме).\r\n</ol>"
name: Малый Иремель
name_alt: null
