coordinates:
- 54.646446
- 58.634641
description: Курумный купол
height: 1360
images:
- comment: Вершина
  image: e48f3a2eadfafd6e418d61f004dca503861863ad.jpeg
interpretation: ''
name: null
name_alt: Круглая
