coordinates:
- 54.956495
- 59.179693
description: "Курумы, тундра, скальный выход\r\n"
height: 1175
images:
- comment: С юго-запада
  filename: cb5b106ece6e8de3938bf67baf3b4ef3bc58d962.jpeg
- comment: На вершине
  filename: b1a6f2a09f4c34a550b57207ab27b1c56005bad4.jpeg
interpretation: null
name: null
name_alt: null
