coordinates:
- 53.620431
- 58.54495
description: Лесистая вершина
height: 1003
images:
- comment: Вершина
  filename: 086dcd35ae3c3614b4b07f3466c0b57c504c026f.jpeg
interpretation: null
name: null
name_alt: null
