coordinates:
- 54.35436
- 58.222902
description: "На вершине холма, представляющего собой альпийский луг &mdash; участок\
  \ горной тундры, курумы, скальные выходы.\r\n"
height: 1333
images:
- comment: Вершина
  image: 249e6960b807b7e28a843a046d81dcae2d1a7faa.jpeg
- comment: Вид с вершины 1
  image: 121b37de5178a38016ba348ca610e953422a91a1.jpeg
- comment: Вид с вершины 2
  image: 90dd705c2bfb39fa8a64d3d76c066d3cb8eaf773.jpeg
interpretation: null
name: null
name_alt: null
