coordinates:
- 55.063756
- 59.525522
description: "Горная тундра, курумы, невысокие скальные останцы\r\n"
height: 1155
images:
- comment: Вершина
  filename: 1516be8bb31146178f9d8073d68d148d618086b1.jpeg
- comment: Вершина
  filename: 7403aa7b484108e7ae975aa26642e2c6e49c86f8.jpeg
interpretation: Первая из трех сопок, считая от Златоуста.
name: Первая Сопка
name_alt: null
