coordinates:
- 53.927091
- 58.574627
description: Весьма мощный скальный гребень. Вершинный тур находится на краю леса,
  в центральной части горы, не осложнённой гребнем.
height: 1019
images:
- comment: Вид с вершины
  image: 6b8fc642234867e5078d0953536ad8e814f1697f.jpeg
- comment: Панорама с вершины
  image: 9a92c358162d23f3f40bfebb85096b105f9d1443.jpeg
- comment: Цирк недалеко от вершины
  image: 3bd2d4fd7d1bd7dad7f99e27ec3ded2091d8d7b3.jpeg
interpretation: "<ol>\r\n<li><b>Корташ</b> (баш.) &mdash; тетеревиный камень. Возможно,такое\
  \ название дано за сходство скального гребня, венчающего гору, с тетеревиным гребешком.\
  \ \r\n<li><b>Курташ</b> (баш.) &mdash; богатый камень &mdash; гора, богатая камнями,\
  \ скалами."
name: Курташтау
name_alt: Курташ
