coordinates:
- 53.589105
- 58.537313
description: Лес, поляна. На восточном склоне, в ущелье Курузяк - скала Огурец
height: 1005
images:
- comment: Вид с вершины
  image: 300c43e19c909bbed1a036e9e4631350e8895f49.jpeg
- comment: Вершина
  image: 537727ded78b8e17aec92828016d72740eaa9665.jpeg
interpretation: <strong>Куру</strong> (тат.) &mdash; голый, пустой. <strong>Зэк</strong>
  (баш.) &mdash; гора.
name: null
name_alt: Курузяк
