coordinates:
- 55.264762
- 59.859646
description: Курумы, скальный выход
height: 1033
images:
- comment: Вершина
  image: 78d86a3c7d12ff947f60420a5bd05c5aaa68410c.jpeg
interpretation: null
name: null
name_alt: null
