coordinates:
- 54.664598
- 58.721716
description: ''
height: 1151
images:
- comment: Вершина
  filename: 408055ba4dc3051118befdd1aa0ffda8d21ff7c8.jpeg
- comment: Панорама с вершины в сторону долины р. Евлакты
  filename: 1492a938f35d228d50df3f5a2b7fdc25317155be.jpeg
- comment: С Тюлюка
  filename: 58f203704375fcf6bb370db0d0f10befd777ee88.jpeg
interpretation: null
name: null
name_alt: null
