coordinates:
- 54.597655
- 58.068183
description: null
height: 1090
images:
- comment: Вид с курумника неподалеку от вершины на запад
  filename: 22f0618bb57b5f5276f63560544d425f6af55f71.jpeg
interpretation: На хребте несколько гор с таким названием. Хребет Сухих Гор - платообразный,
  лесистый, с многочисленными параллельными отрогами, расчленёнными речками и ручьями,
  берущими своё начало на склонах основного хребта. На вершинах, находящихся на плато,
  источников воды нет.
name: Сухая
name_alt: null
