coordinates:
- 54.847655
- 59.156421
description: ''
height: 1019
images:
- comment: Вид на вершину с Большого Нургуша
  filename: 953a77aa2c2f8b6e0eb99c0b1cdfb29029600b79.jpeg
interpretation: null
name: null
name_alt: null
