coordinates:
- 54.416947
- 58.470973
description: ''
height: 1113
images:
- comment: Вершина
  image: 85c925aa18e560374ecf4b899e1c46d65d4c178a.jpeg
- comment: Вид с вершины
  image: 01f741a5e2aa96cbb08fa32bbfc66b93cf481cd7.jpeg
interpretation: ''
name: null
name_alt: null
