coordinates:
- 54.39592
- 58.477334
description: Невысокая скала, редколесье.
height: 1079
images:
- comment: Вершина
  filename: 85d4579e2ed91a8b695f53235faabaf8543ec8dc.jpeg
interpretation: null
name: null
name_alt: null
