coordinates:
- 54.270942
- 58.318627
description: Скальная башня
height: 1079
images:
- comment: Вершина
  image: 7b9082918c3605bbff2421e43a51ff19ef4d2c60.jpeg
interpretation: ''
name: null
name_alt: null
