coordinates:
- 55.273913
- 59.783809
description: null
height: 1041
images:
- comment: Вершина
  filename: 9973fef056e62fc7a5ae1dbf32d6c20a13fadd15.jpeg
interpretation: '<b>Двуглавая</b> &mdash; две вершины. <b>Сопка</b> &mdash; гора с
  округлой вершиной. '
name: null
name_alt: Двуглавая Сопка-Север, Малый Таганай, Таганай, Ближний Таганай, Бараньи
  Лбы, Правая Сторона
