coordinates:
- 54.358179
- 58.376746
description: "Редколесье, курумы\r\n"
height: 1215
images:
- comment: Вершина
  filename: 0776de5f2adbbd786f861cda98903a2f430bce18.jpeg
interpretation: null
name: null
name_alt: null
