coordinates:
- 54.070384
- 57.88248
description: "Курум, скальный выход\r\n"
height: 1093
images: []
interpretation: <strong>Дунэн</strong> (баш.) &mdash; жеребец (трехгодовалый). <strong>hуйган</strong>
  (баш.) &mdash; зарезали. <strong>Сую</strong> (тат.) &mdash; резать. Жеребца зарезали
name: Дунян-Сунган
name_alt: Дюнян-Суйган
