coordinates:
- 55.038097
- 59.50172
description: "Вытянутый по оси хребта курумный купол, выходы скальных пород\r\n"
height: 1198
images:
- comment: Вершина
  filename: c72b0433ef49dee7f4b01b15537872934721770b.jpeg
- comment: Вершина
  filename: 4aaac24e4df699fc24fcd06285e94d1097db000b.jpeg
- comment: Вершинный тур
  filename: e6576aa619e8fa046e7c20f4f5de7ea7fbdd8f18.jpeg
- comment: Вершина
  filename: bd52cb4d45ff4ad5c5fd8453c18d73d53ef97c48.jpeg
interpretation: Вторая &mdash; средняя из трех сопок, считая от Златоуста. Голая &mdash;
  мало растительности.
name: Вторая Сопка
name_alt: Голая Гора
