coordinates:
- 54.23965
- 58.124493
description: Огромный курумный купол &mdash; "кабан", на горнотундровом плато &mdash;
  скальный выход. Третья по высоте вершина Южного Урала.
height: 1519
images:
- comment: Вершина
  image: ab830deb1b9acf80fdc24ab43dc8c1e421cf607a.jpeg
- comment: Вершина
  image: ab1259242e8297a1513e3f9a77dcda15961106a3.jpeg
interpretation: <strong>Яман</strong> (баш.) &mdash; плохой, дурной, <strong>тау</strong>(баш.)
  &mdash; гора. Плохая, дурная гора (глухие места, болото, постоянно лежит снег, облака,
  туман). <strong>Куянтау</strong> - заячья гора.
name: Малый Ямантау
name_alt: Куянтау
