coordinates:
- 54.194847
- 57.962198
description: null
height: 1171
images: []
interpretation: "<b>Нер</b> (манси) &mdash; каменистая вершина. <b>Таш</b> (баш.)\
  \ &mdash; камень.\r\n"
name: Нараташ
name_alt: Нары-Таш, Медвежья
