coordinates:
- 54.801081
- 58.932939
description: "Отрог горы Уван. Курумы, скальный выход\r\n"
height: 1106
images:
- comment: Вершина
  filename: b5f4ec7b5de527c28a02df05eaf5087a32b4f290.jpeg
- comment: Вершина
  filename: 238198fc342e71c4904384c0be2c6173e5468b4d.jpeg
interpretation: null
name: null
name_alt: Малый Уван
