coordinates:
- 55.286679
- 59.789829
description: 'Отдельно стоящие скалы-останцы

  скальный гребень

  скальный гребень'
height: 1027
images:
- comment: Вершина
  filename: 9f7ae487f55480ae318006cb553ddd6861133485.jpeg
interpretation: null
name: null
name_alt: Три Сестры, Митькины Скалы
