coordinates:
- 54.545765
- 58.920852
description: "Курумы, скальный выход\r\n"
height: 1345
images:
- comment: Панорама с вершины
  filename: 5eede8b66512a851a3da10126a538911fc4803fd.jpeg
interpretation: null
name: null
name_alt: null
