coordinates:
- 53.709889
- 58.595692
description: "Невысокая скала вулканических пород, редколесье\r\n"
height: 1015
images:
- comment: Вид на вершину с г. Кушай
  filename: 6b215c0b5822bcf6c9d96797490c0885948b27c6.jpeg
- comment: Вид с вершины
  filename: a38b85dc4c6dd881de8e0f447007202116c08aab.jpeg
interpretation: <strong>Бабай</strong> (баш.) &mdash; дедушка, старейшина. <strong>Таш</strong>
  (баш.) &mdash; камень.
name: Бабай
name_alt: Бабай-Таш
