coordinates:
- 55.296118
- 59.810758
description: Мощный, протяжённый скальный гребень. Пожалуй, самый мощный и красивый
  на Южном Урале.
height: 1155
images:
- comment: Откликной гребень
  filename: 1fecb2b61889bde0d296080386157edcb80d2db7.jpeg
- comment: Вершина
  filename: 401efce150dc4038767b735138ba864ddeb086fd.jpeg
interpretation: Скалы похожи на гребень. В скалах возникает многократное (семикратное)
  эхо.
name: Откликной Гребень
name_alt: Откликная, Перекликной Лог, Большой Гребень
