coordinates:
- 54.981195
- 59.217095
description: "Курумы, тундра, скальный выход\r\n"
height: 1160
images:
- comment: Вершина
  filename: 59e6ddb24a7ab1270cb3421185e9bc3aca67795b.jpeg
interpretation: null
name: null
name_alt: null
