coordinates:
- 55.268277
- 59.851057
description: "Курумы, скальный выход\r\n"
height: 1025
images:
- comment: Вершина
  image: 22a79efb6fced11320e20adfd5cd6406332655d5.jpeg
- comment: На вершине
  image: 89b4fc52b2441e903a31b5bfdc7d66c22cbf0e97.jpeg
interpretation: <b>Монблан</b> &mdash; &laquo;белая гора&raquo;, вершина в Западных
  Альпах, самая высокая в Западной Европе. Название дано за снежную шапку вершины.
  Уральское название дано по аналогии и связано с тем, что с вершины, хотя она и не
  самая высокая, открывается вид на все окрестные хребты
name: null
name_alt: Монблан
