coordinates:
- 54.624783
- 58.638536
description: ''
height: 1215
images:
- comment: Курумная поляна недалеко от вершины
  image: 416f52a37e91c2522bc2e925ab62a9b8bd5841b2.jpeg
interpretation: null
name: null
name_alt: null
