coordinates:
- 54.75223
- 59.196061
description: "Лес, полянка, небольшой обрывчик на северо-восток\r\n"
height: 1116
images: []
interpretation: "<ol>\r\n<li><b>Ялауды</b> (баш.) &mdash; облизанная гора (<b>ялау</b>\
  \ (баш.) &mdash; лизать, облизать).\r\n<li><b>Елау</b> (баш.,тат.) &mdash; плач.</li>\r\
  \n</ol>"
name: Еловда
name_alt: Елавда, Ивалда, Елауды, Евлавда
