coordinates:
- 53.624888
- 57.592333
description: Скальный гребень, состоящий из огромных каменных плит, расположенных
  наклонно и сложенных сланцевыми породами.
height: 1043
images:
- comment: Вид с вершины
  image: cba3cb89dda3d94a11c84703f0b6f28ea046edbb.jpeg
- comment: Вершинный тур
  image: c2a5f71ca254524e922a695f986c542b52958206.jpeg
interpretation: null
name: Катушка
name_alt: null
