coordinates:
- 54.260054
- 58.355946
description: Одна из скал-бастионов (столбов), по которым хребет, собственно, и получил
  своё имя.
height: 1077
images:
- comment: Вершина
  filename: c91f68c743a6005d3b7d71af49fb30ff90fd9e6f.jpeg
interpretation: null
name: null
name_alt: null
