coordinates:
- 54.589442
- 58.040776
description: "<p>Еловый лес, расчищенное от деревьев место под триангуляционный знак,\
  \ останки которого лежат рядом, короткая просека от вершины на восток.</p>\r\n\r\
  \n<p>Гора имеет как-бы две вершинки. Первая (более низкая) &mdash; курумная, со\
  \ скалами, расположенными разорванным полукольцом, напоминающим основание разрушенного\
  \ замка &mdash; она-то и носит название <b>Каменный Форфос</b>. Вторая - 1164 -\
  \ покрыта еловым лесом."
height: 1164
images:
- comment: Вид на вершину с г. Сухая
  image: ddc5ba26d6acf0adbc499f66731e7602292f4d85.jpeg
- comment: Неподалеку от вершины
  image: 93ad8fd3d16f3a62e82198a1ba6f59dcc0add78c.jpeg
interpretation: "Название, собственно, относится ко второй, более низкой вершине (1136),\
  \ где находится полукольцо скал оригинального строения, напоминающее крепостную\
  \ стену. Искажённое &laquo;форпост&raquo;. По легенде Пугачёв и Салават Юлаев в\
  \ этом &laquo;форпосте&raquo; строили планы захвата Катав-Ивановска.\r\n"
name: Каменный Форфос
name_alt: Большой Каменный Форфос
