coordinates:
- 55.33035
- 59.959298
description: "Невысокие скалы посреди горнотундровых склонов\r\n"
height: 1049
images:
- comment: Вершина
  image: e1fb5aefdcb4e6722e96a63812e19435c5109e4b.jpeg
- comment: Вершина (справа)
  image: b6e945606e1304cc3b602625445f412c757d7077.jpeg
interpretation: <b>Иссиль</b> (баш.) &mdash; вечный ветер. <b>Иссеу</b>(баш.) &mdash;
  дуть. <b>Ел</b> (баш.) &mdash; ветер. Гора ветров
name: Ицыл
name_alt: null
