coordinates:
- 53.645194
- 58.535445
description: Скальный выход
height: 1080
images:
- comment: Вид с вершины 2
  image: 181b0397f053a3a9b1c7f00bc64757324b6d6478.jpeg
- comment: Вершина (вид с запада)
  image: 61da896eabcc5b99ca745e473e7480baa2a212ea.jpeg
- comment: Вид с вершины
  image: cabffedcc2978a5100cc4d7e867c7fd5f8b304cd.jpeg
interpretation: <b>Кусимов</b> - глава башкирского рода, основатель поселения (деревни
  Кусимово), лежащего неподалеку.
name: Кусимова
name_alt: Кусимовка, Аумыш-Таш
