coordinates:
- 54.491568
- 57.865009
description: null
height: 1016
images:
- comment: Вершина (с хребта Байрамгул)
  image: 5bba7b9ba1c03df3ebb4ebf83bdd4fb5d0429ab3.jpeg
- comment: Вершина
  image: 305461faeefb21d3dbd372430f881d238b762afa.jpeg
interpretation: "<ol>\r\n<li><b>Саля</b> (ненец.) &mdash; мыс.</li>\r\n<li><b>Сил</b>\
  \ (баш.) &mdash; тихий, спокойный. Затишье, нет ветра. <b>Яз</b>, <b>уяз</b> (баш.)\
  \ &mdash; долина, тихая долина.</li>\r\n<li><b>Сылыу</b> (баш.) &mdash; место, богатое\
  \ водой</li>\r\n</ol>\r\n"
name: Саля
name_alt: null
