coordinates:
- 54.364094
- 58.24264
description: "Курумы, скальный выход, лес\r\n"
height: 1303
images:
- comment: Вершина
  image: e5ae581282d36ae04a06589010b9557d2ba3b7c9.jpeg
- comment: Вид с вершины
  image: 2c0bd636cdd57f3dc2f97b68d1609f58d5788603.jpeg
interpretation: <strong>Карауыл</strong> (баш.) &mdash; место для наблюдения. С вершины
  &mdash; небольшого скального уступа &mdash; удобно наблюдать за местностью, к примеру
  выслеживая дичь.
name: Караульный Камень
name_alt: null
