coordinates:
- 54.256017
- 57.830293
description: Скальный выход, курумы
height: 1170
images:
- comment: Вершина
  image: 4489f4f47fc142d0fda6bbc81e36c1961c57b59f.jpeg
- comment: Вид с вершины
  image: 5c5b7a8c6416f6a49d5bf52322088f8a19f6b337.jpeg
interpretation: null
name: null
name_alt: null
