coordinates:
- 54.575656
- 58.006872
description: 'Вершина находится на плато

  горный луг, камни

  хороший вид на Шелома, Нары.'
height: 1138
images:
- comment: Вершина 1138. Вид с г. Каменный форфос
  filename: 79deac0828fd060b8fd88e60d986a21338b4de4d.jpeg
interpretation: null
name: null
name_alt: Плато-2
