coordinates:
- 54.136754
- 58.277201
description: Группа скальных стен, отвесных к западу
height: 1129
images:
- comment: Вид с вершины в сторону Ямантау
  image: 2a15621ffd9f250164675394a441b8f220708578.jpeg
- comment: Вершина
  image: e4d0158fe96c60a69fc6fd8e19e0bae7c2541340.jpeg
interpretation: null
name: Мохнатка
name_alt: null
