coordinates:
- 54.243273
- 57.817457
description: Пологая и лесистая, с северо-запада обрывается протяжённой скальной стеной
  на юго-восток
height: 1137
images:
- comment: Вершина
  filename: 4638d4fc6b389f5046ec2c2734484988f65f2320.jpeg
interpretation: null
name: null
name_alt: null
