coordinates:
- 55.477293
- 59.986226
description: Лесистая вершина. Стоит триангуляционная вышка из старых брёвен.
height: 1003
images:
- comment: Вид в сторону вершины со стороны Чертовых ворот
  image: c59820e2606252d9141dffa24c7015c8d3706ec7.jpeg
interpretation: "<ol>\r\n<li><b>Йур</b> (баш.,тат.) &mdash; ходить, <b>ма</b> &mdash;\
  \ суффикс отрицания. <b>Юрма</b> &mdash; не ходи.</li>\r\n<li><b>Йурме</b> &mdash;\
  \ дремучий лес. Склоны горы труднопроходимы из-за густого леса.</li>\r\n<li><b>Урема</b>,\
  \ <b>урман</b> (русские уральцы) &mdash; болотистый, дремучий лес.</li>\r\n<li><b>Юрмэ</b>\
  \ &mdash; род мясного кушанья</li>\r\n</ol>\r\n"
name: Юрма
name_alt: null
