coordinates:
- 54.150544
- 57.995087
description: null
height: 1103
images: []
interpretation: <b>Кара</b> (баш.,тюрк.) &mdash; тёмный, чёрный, но в случае употребления
  к горам указывает на безлесость, пустынность. <b>Таш</b>(баш.) &mdash; камень, гора.
  По смыслу можно перевести как &laquo;безлесая вершина с камнями, скалами&raquo;.
name: Караташ
name_alt: null
