coordinates:
- 54.347448
- 58.359967
description: Горнотундровое плато, курумы, скальный гребешок. Между вершинами 1317,
  1265 и 1287 лежит верховое болото, с которого "вытекает" курум Широкая Россыпь -
  один из самых мощных на Южном Урале
height: 1287
images:
- comment: Вид с вершины
  image: c962bfa82a784f486745206099886335abf6e111.jpeg
- comment: Панорама в сторону Широкой россыпи
  image: 8be48598bc275324a795744d77317fccff3b51be.jpeg
- comment: Вид с вершины 2
  image: 932a2c9e0f22994e4597bf8a9f338f9482767589.jpeg
interpretation: На Южном Урале часто горы с большими столообразными вершинами называли
  &laquo;широкими&raquo;.
name: Широкая
name_alt: null
