coordinates:
- 54.812755
- 58.833418
description: "Скальный выход, курумы\r\n"
height: 1190
images:
- comment: Вершина
  filename: 156cdb4c55b3afb0f1d394769966886b6546ecbe.jpeg
interpretation: null
name: null
name_alt: null
