coordinates:
- 54.596235
- 58.531678
description: "Лесотундровое плато с невысокой скалой\r\n"
height: 1237
images:
- comment: Вид на вершину с г. Глухаринная
  filename: 58834767be4e76f97e9fab524594e76dc1f588f3.jpeg
interpretation: Прежде на горе долго лежал снег
name: Мерзлый Утес
name_alt: null
