coordinates:
- 53.584736
- 58.479143
description: null
height: 1043
images:
- comment: Вершина
  filename: ab13d01175588922c2984999a6878179b246c701.jpeg
interpretation: <b>Кара</b> (баш.,тюрк.) &mdash; тёмный, чёрный, но в случае употребления
  к горам указывает на безлесость, пустынность. <b>Таш</b>(баш.) &mdash; камень, гора.
  По смыслу можно перевести как &laquo;безлесая вершина с камнями, скалами&raquo;.
name: Караташ
name_alt: Южный Салават
