coordinates:
- 54.679269
- 58.698461
description: Плато с небольшими останцами
height: 1270
images:
- comment: Вершина
  filename: bab915bfb77f785bb865342d957c58bbbacf6edd.jpeg
interpretation: ''
name: null
name_alt: null
