coordinates:
- 53.773452
- 58.326679
description: "Крутая, лесистая. Есть осыпи, выход вулканических пород\r\n"
height: 1068
images:
- comment: С запада
  filename: 5fe3b78f94475983e0e9a441caf988ed6546e77e.jpeg
- comment: Вершина
  filename: 8b91c18ad4de7fdb4135d01c6ecf62a675a15e77.jpeg
- comment: Вершина
  filename: b38f259f868b8e1da6b2e4114618ae1de083c394.jpeg
interpretation: 'Гора называется по двум рекам берущим около нее начало: <strong>Арвяк</strong>
  и <strong>Рязь</strong>.'
name: Арвякрязь
name_alt: Рязь, Рязьташ, Арвяк
