coordinates:
- 54.848531
- 59.072845
description: "Небольшая скальная гряда в лесу\r\n"
height: 1029
images:
- comment: На вершине
  filename: 03969d091c271b93734ea1238f16bf9599b9707a.jpeg
- comment: Вид с вершины на Нургуш
  filename: dcfa8ac0d3ba05c1aaaf585b6e5d2e10d0548409.jpeg
interpretation: null
name: null
name_alt: null
