coordinates:
- 54.550357
- 58.408813
description: "Курумный купол\r\n"
height: 1282
images:
- comment: Вершина
  filename: 1e349ce3e2a88f1ca205b8ff9425bd0945ec8357.jpeg
- comment: Вершина. Вид с отрога г. Большой Пасынок
  filename: 02e633a3b21e9bb5473e838d93d10e6e56bb940e.jpeg
interpretation: <strong>Шелом</strong> &mdash; шлем, холм, бугор.
name: null
name_alt: Пятый Шелом
