coordinates:
- 54.39123
- 58.28986
description: Небольшой курумный купол на плато в лесу, скальный выход на вершине.
height: 1261
images:
- comment: Вершина
  filename: eda304d380b7c7ad2c59fcd19ce065b89326bc13.jpeg
interpretation: null
name: Кобея
name_alt: null
