coordinates:
- 54.807449
- 58.83769
description: "Курумы, скальный выход\r\n"
height: 1168
images:
- comment: Вершина
  image: ad7a95a1d855efe3500ebf39908f44b1da0fb1bc.jpeg
interpretation: null
name: null
name_alt: null
