coordinates:
- 53.63165
- 58.522684
description: Невысокая скала вулканических пород, редколесье.
height: 1013
images:
- comment: Вершина
  filename: 2bbe9616773be6e8984cc4b87a579882f62bacaa.jpeg
interpretation: null
name: null
name_alt: Южная Кусимовка
