coordinates:
- 54.585682
- 58.581994
description: "Курумы, скальные выходы\r\n"
height: 1198
images:
- comment: На вершине
  image: c2790204480b3903f3e1a0d1cfb4accfb376d903.jpeg
- comment: Вершина. Вид с отрога Пасынка 1048
  image: 032aae17708505ff95734a67eea4f832cd09f679.jpeg
interpretation: <strong>Пасынок</strong> &mdash; неродной, отрог хребта
name: Большой Пасынок
name_alt: null
