coordinates:
- 53.684149
- 57.647573
description: Редколесье, лесостепь. Скальный гребень, состоящий из огромных каменных
  плит, расположенных наклонно и сложенных сланцевыми породами
height: 1142
images:
- comment: Вершина
  filename: 46f6d23d64baf30c6d32cf78a4b54ce02707105a.jpeg
interpretation: Возможно, слово <strong>маяк</strong> употреблено местным населением
  в значении &laquo;передовой&raquo;, как один из &laquo;пяти склонов, подолов&raquo;
  (см. <a href="/summit/211">&laquo;Бишетек&raquo; &mdash; Большой Шатак</a>). Или
  как точка, откуда открывается вид на окружающую местность
name: Большой Таштырт
name_alt: Маяк
