coordinates:
- 54.880084
- 58.909018
description: Узкий курумный гребень
height: 1139
images:
- comment: Вершина
  image: a1df6a64a28dcd66f252433097d0a95ec868a8e2.jpeg
interpretation: null
name: null
name_alt: null
