coordinates:
- 53.597904
- 58.494208
description: Скальный выход
height: 1108
images:
- comment: Вершина
  image: 191033988d71824b5b40eccabc97b3c0838ed3c2.jpeg
- comment: Вершина
  image: a488822485ae918f7896a1a30e329e8aeeff399a.jpeg
interpretation: "<p><b>Шыршил</b>, <b>шершил</b> (баш.) &mdash; еловая, <b>тау</b>\
  \ (баш.) &mdash; гора. <b>Таш</b> (баш.) &mdash; камень.</b></p>\r\n\r\n<p><b>Салаватские\
  \ Камни</b> &mdash; в честь народного героя Салавата Юлаева или просто от башкирского\
  \ имени.</p>"
name: Шершилтау
name_alt: Шершалы-Таш, Салаватские Камни
