coordinates:
- 54.61395
- 58.563648
description: Лесотундровое плато с невысокой скалой
height: 1235
images:
- comment: На вершине. Вид в сторону г. Поперечной
  filename: b94793c4f033cbbe2310319e77a1c4a25f48b53f.jpeg
interpretation: ''
name: null
name_alt: Мерзлая
