coordinates:
- 53.725678
- 57.680436
description: null
height: 1069
images:
- comment: Вершина
  image: 5b5713c5cff1329b4115b60d820d1396623b0f62.jpeg
interpretation: <b>Япрак</b> (баш.) &mdash; лист. <b>Таш</b> (баш.) &mdash; камень.
  Разбитый камень.
name: Яракташ
name_alt: null
