coordinates:
- 54.117416
- 58.182673
description: ''
height: 1086
images:
- comment: Вид с вершины
  filename: 27d1cae4aa87cda95cd1372c660595f29449ffad.jpeg
interpretation: ''
name: null
name_alt: null
