coordinates:
- 54.391603
- 58.484259
description: ''
height: 1069
images:
- comment: На вершине
  image: 3f3a2760db784aab87d80cc205bfd46a76bab07a.jpeg
- comment: Вершина
  image: 5eecce431b52e87e252d93a064f99c5f072a93cd.jpeg
interpretation: ''
name: null
name_alt: Белый Камень
