coordinates:
- 53.648005
- 58.509158
description: Лесостепь, камни, выход вулканических пород
height: 1040
images:
- comment: Вид с вершины
  image: 5fdb164bfbe15ff5490fb4c7ee532efcf1ff3e87.jpeg
interpretation: <b>Дальняя</b> &mdash; по расположению.
name: null
name_alt: Дальняя
