coordinates:
- 54.331168
- 58.326787
description: Курумы. Между вершинами 1317, 1265 и 1287 лежит верховое болото, с которого
  &laquo;вытекает&raquo; курум Широкая Россыпь - один из самых мощных на Южном Урале
height: 1317
images:
- comment: Вершина
  filename: 82c00fd6c1068d7296bf3aa620c7d7eaa2f64371.jpeg
interpretation: null
name: null
name_alt: null
