coordinates:
- 54.527856
- 58.95298
description: Лесистая вершина
height: 1185
images:
- comment: Вид с вершины
  filename: 6534cb27554665f35666baeba7923922a286bc3c.jpeg
interpretation: "<strong>Шыршыл</strong>, <strong>шершил</strong> (баш.) &mdash; еловая,\
  \ <strong>бийик</strong>, <strong>бейек</strong> (баш.) &mdash; высотка, возвышенность.\r\
  \n"
name: Большой Шаршалыбиик
name_alt: null
