coordinates:
- 54.813477
- 59.125992
description: Разрушенные скалы
height: 1393
images:
- comment: Вершина (вид с севера)
  filename: e2307846bb793e1b737b349bea4d981e3fae36df.jpeg
- comment: Вершина (вид с юга)
  filename: 020000aad304abfc6da5c2af329baf58663e2785.jpeg
interpretation: ''
name: null
name_alt: null
