coordinates:
- 54.254786
- 58.103753
description: "Огромный курумный купол &mdash; &laquo;кабан&raquo;, на протяжённом\
  \ горнотундровом плато &mdash; скальный выход. Высшая точка Южного Урала.\r\n"
height: 1640
images:
- comment: Вид на вершину с Ялангаса
  filename: ac8d889b6350d9bb443fd8c0649aed2c3a4c310f.jpeg
- comment: Вершина
  filename: cd0e695794a142bf755c41baba22f53ad89655eb.jpeg
- comment: С цирка Инзерских зубчаток
  filename: 5d73d83c8c3779173229396fddd3778e711ec45e.jpeg
- comment: Вид на вершину с Большого Нургуша
  filename: 546ecea991477192656e09a4aa6563955ddff167.jpeg
interpretation: <strong>Яман</strong> (баш.) &mdash; плохой, дурной, <strong>тау</strong>(баш.)
  &mdash; гора. Плохая, дурная гора (глухие места, болото, постоянно лежит снег, облака,
  туман)
name: Ямантау
name_alt: null
