coordinates:
- 54.325732
- 58.214756
description: "Курумный купол, скальный выход. С запада лес подходит близко к вершине\r\
  \n"
height: 1370
images:
- comment: Вершина
  filename: 62b711d8342a6f82466292bdd75f36bb32093264.jpeg
- comment: Вид с вершины 1
  filename: d448a3be4939e637ab8086a8f00be1258be66b24.jpeg
- comment: Вид с вершины 2
  filename: 2457d4ddf328a8faaf2ec63555f97da89638b738.jpeg
- comment: Вид с вершины 3
  filename: 3da1c5b83342188a9db219dc9fa50535d9b86c8c.jpeg
interpretation: <strong>Широкий</strong> в смысле обширный.
name: Широкий Машак
name_alt: null
