coordinates:
- 54.425442
- 58.318724
description: 'Глухие места, обитали медведи

  курумный купол

  '
height: 1300
images:
- comment: Вершина (слева)
  filename: 857a0dcc43d1103395838172375b2dd4174f346c.jpeg
interpretation: null
name: null
name_alt: Медвежья-2
