coordinates:
- 54.535264
- 58.835345
description: "Горнотундровое плато\r\n"
height: 1320
images:
- comment: Вид с Большого Иремеля
  image: 32c4906f9e2dc05c863f40776f6259be5e275e23.jpeg
interpretation: <b>Залавок</b> &mdash; старинный русский орографический термин &mdash;
  ровное пространство значительной величины на склоне вершины, плато, уступ.
name: null
name_alt: Залавок, Кругозор, Обзорная, Панорамная
