coordinates:
- 54.325631
- 58.36918
description: Горнотундровое плато,скальные останцы. Между вершинами 1317, 1265 и 1287
  лежит верховое болото, с которого &laquo;вытекает&raquo; курум Широкая Россыпь &mdash;
  один из самых мощных на Южном Урале
height: 1265
images:
- comment: Панорама вершины
  image: 7108997ef07e5d28af196734490690bb709d358f.jpeg
- comment: Вид на вершину с г. Б. Кумардак
  image: c6bb7c2b7508eeb759f6c85246799af1e0973787.jpeg
interpretation: Глухие места, обитали медведи
name: Машак
name_alt: Медвежья
