coordinates:
- 54.43645
- 58.600522
description: С восточной стороны - мощные скальные стены протяжённостью несколько
  километров
height: 1037
images:
- comment: Вид с вершины
  image: 5aeab35c3f560d9a55f4c0f391877676a22ceabf.jpeg
- comment: Вершина (вид с г. Б. Кумардак)
  image: f7281d444737f46adbc6ff0fb8741d373011b61e.jpeg
- comment: Вершина
  image: 02933ad5468cfb2b5bafb5c1f4590bb1a9ee480a.jpeg
interpretation: null
name: null
name_alt: null
