coordinates:
- 54.789206
- 59.086981
description: "Курумный купол, скальный гребешок\r\n"
height: 1350
images:
- comment: Вершина
  image: 7d72059c3b4b5cf1a40d82ebb2f4ac0ea912efbe.jpeg
- comment: На вершине
  image: d90440ae2a83ba024f2706126afcb24623c8558d.jpeg
interpretation: "<ol>\r\n<li><b>Нур</b> (баш.) &mdash; луч, сияние. <b>Кош</b>, <b>гуш</b>,\
  \ <b>куш</b> (баш.) &mdash; птица. Лучезарная, сияющая птица.\r\n<li><b>Нуру</b>,\
  \ <b>нура</b> (древний тюрко-монгольский) &mdash; хребет, горная цепь, гора. <b>Кош</b>,\
  \ <b>гуш</b>, <b>куш</b> (баш.) &mdash; птица. Птичий хребет"
name: null
name_alt: Нургуш-2
