coordinates:
- 54.798629
- 58.806218
description: "Маленький курумный купол, скальный выход\r\n"
height: 1039
images:
- comment: Вершина
  filename: af60a4a9ad9cd418f721e137df84c0562d932acf.jpeg
interpretation: null
name: null
name_alt: null
