coordinates:
- 54.54617
- 58.778448
description: Курумы, скалы
height: 1183
images:
- comment: Вершина
  image: eb99c3684a27afd0ad9c89a60eecab002f16d524.jpeg
- comment: Вершина
  image: 6f9047c96ab7edae352b731afcd6e24acc75541e.jpeg
interpretation: От русского жеребец
name: Жеребчик
name_alt: null
