coordinates:
- 53.778576
- 58.045382
description: Лес, плато. Старая вышка
height: 1038
images:
- comment: Вышка на вершине
  image: efa1f52506101f5b37f229ebddf0f63ecf846e4d.jpeg
interpretation: null
name: null
name_alt: null
