coordinates:
- 55.270733
- 59.774308
description: Скальный бастион. На горе много скал останцев, формой напоминающих перья
height: 1034
images:
- comment: Вершина
  filename: 1be98635c48230285541ead8460042b7b54e5c31.jpeg
- comment: С юга
  filename: 06b9f168e7bb4765cb1b1348edf61b6822da1797.jpeg
interpretation: <b>Двуглавая</b> &mdash; две вершины. <b>Сопка</b> &mdash; гора с
  округлой вершиной.
name: Малый Таганай
name_alt: Двуглавая Сопка-Юг, Малый Таганай, Ближний Таганай, Перья, Левая Сторона
