coordinates:
- 54.581239
- 58.506201
description: Скала-останец
height: 1114
images:
- comment: Вершина
  image: d02076c2b0d3710300f8bfa576ad19d8f8e23f55.jpeg
- comment: Вид на г. Глухаринная с г. Антенная
  image: 1cb8933e8ea407c7940899b6cc7be85bef427e2b.jpeg
interpretation: null
name: Глухариная
name_alt: null
