coordinates:
- 54.344431
- 58.175017
description: "Небольшой курумный купол, редколесье, скальный выход\r\n"
height: 1268
images: []
interpretation: "Небесспорные версии:\r\n<ol>\r\n<li><b>Башак</b>, <b>ашак</b> (баш.)\
  \ &mdash; колос.\r\n<li><b>Ук башагы</b> (баш.) &mdash; наконечник стрелы.\r\n</ol>"
name: Машак
name_alt: null
