coordinates:
- 54.637392
- 58.601442
description: "Курумный купол\r\n"
height: 1240
images:
- comment: Вершина
  image: 86df203f62fe8ab5ab87259ee48e9b6af7db8519.jpeg
- comment: Вершина
  image: 3f095f622d0284553639c4a904665e6ab84bab65.jpeg
interpretation: Дол &mdash; понижение, небольшая долина с пологими склонами. Возможно,
  гора названа по долу ручья Большой Каменный, в верховьях которого она находится.
  Мохнатый &mdash; лесистый &mdash; в противопоставление болоту Чёртов Дол, лежащему
  неподалеку и поросшему низкорослыми берёзками.
name: Мохнатый Дол
name_alt: null
