coordinates:
- 54.749663
- 59.001018
description: "Курумный купол, скальный выход\r\n"
height: 1247
images:
- comment: Вид на вершину с кордона "у трех вершин"
  image: b0d1d85c858262c4d3e6e0012fabc0b92b5606a3.jpeg
interpretation: null
name: null
name_alt: null
