coordinates:
- 54.545191
- 58.390749
description: "Курумный купол\r\n"
height: 1293
images:
- comment: Вершина
  image: a6495bb1e6c81518745732146e6c1d49679e69a4.jpeg
interpretation: <strong>Шелом</strong> &mdash; шлем, холм, бугор.
name: null
name_alt: Четвертый Шелом
