coordinates:
- 53.605577
- 58.039127
description: "Лесистое плато\r\n"
height: 1037
images:
- comment: Старая вышка
  image: 3f05b18cc3567d1c2e4976ed5b9f9e9d3f8a5b8a.jpeg
interpretation: null
name: null
name_alt: null
