coordinates:
- 54.429533
- 58.324192
description: 'Глухие места, обитали медведи

  курумный купол

  '
height: 1308
images:
- comment: Вершина (справа)
  filename: 15160475146e24a2f8b0dc71441c79e80833ed14.jpeg
interpretation: null
name: Медвежья
name_alt: Медвежья-1
