coordinates:
- 54.126497
- 58.047706
description: null
height: 1124
images: []
interpretation: <strong>Туркаташ</strong> (тюрк.) &mdash; стоячий камень, прямой камень.
  <strong>Тора</strong>(баш.) &mdash; стоячий, <strong>таш</strong> (баш.) &mdash;
  камень.
name: Туркаташ
name_alt: null
