coordinates:
- 54.439647
- 58.334642
description: Лес, скальный выход
height: 1226
images:
- comment: Вершина
  filename: 451514c220f95d90aa8057c75a6b1e2bf94592be.jpeg
interpretation: null
name: null
name_alt: null
