coordinates:
- 54.951324
- 59.151979
description: Вершина представляет собой почти правильный конус.
height: 1055
images:
- comment: Вершина. Вид сверху (фото с дрона С. Филиппова)
  image: be48080ee0783b337d8e6f84573bd5140d3aa573.jpeg
- comment: Вершина
  image: 6a10f9ff92ae61b6ffc3307cbab5bfe0ee29c312.jpeg
interpretation: Короткая, круглая-по форме. <b>Шишка</b> &mdash; конусообразная гора,
  островерхая гора. <b>Голая</b> &mdash; в данном случае безлесая, сплошь покрытая
  курумами. <b>Сопка</b> &mdash; гора с округлой вершиной.
name: Голая Сопка
name_alt: Круглая Шишка, Короткая Шишка
