coordinates:
- 54.536211
- 58.370929
description: "Большой курумный купол, скальный выход.\r\n"
height: 1368
images:
- comment: Вершина
  image: 97fe8d9694bd42de3da048bc0e3e8937d3f46470.jpeg
- comment: Вершина (слева)
  image: e5b07c59485006a16251a955245fb7904f32e448.jpeg
interpretation: <strong>Шелом</strong> &mdash; шлем, холм, бугор.
name: Малый Шелом
name_alt: null
