coordinates:
- 54.539422
- 57.942561
description: "Вершина горы - скальный выход на лесистом плато, разрушенная вышка.\
  \ Южный склон - полянки, курумы.\r\n"
height: 1153
images:
- comment: Вид на вершину с г. Глинка
  image: d46f42cf4bf9ac82568250d60431dddf1f7b93b6.jpeg
interpretation: "Веселые горы &mdash; в смысле радующие взгляд\r\n"
name: Веселая
name_alt: null
