coordinates:
- 54.517993
- 58.936415
description: Лесистая вершина
height: 1176
images:
- comment: Вид с вершины Байкальская (в сторону Шаршалыбиика)
  filename: 7cad6a7539d6b4d9699330f06c6b5b78c1fde186.jpeg
- comment: Вид с Байкальской на Иремель (справа) и Средний Аваляк (слева)
  filename: 7126a0f824320e7635d212c2bb324c3622117e81.jpeg
interpretation: "<strong>Шыршыл</strong>, <strong>шершил</strong> (баш.) &mdash; еловая,\
  \ <strong>бийик</strong>, <strong>бейек</strong> (баш.) &mdash; высотка, возвышенность.\r\
  \n"
name: Байкальская
name_alt: Южный Шаршалыбиик
