coordinates:
- 53.153684
- 57.251655
description: Плато, поросшее низкорослыми деревьями, с четырьмя вершинками. Главная
  вершина обрывается скальной стеной на юг. Одна из вершинок горы - скальная стена,
  возможно с ней и связано название &laquo;кызлар-таш&raquo;. Останки разбившегося
  самолёта.
height: 1040
images:
- comment: Вершина
  filename: 9745789e96182a1be63a6671c781648e79178326.jpeg
interpretation: "<p>По имени персонажа башкирского эпоса <strong>Масемхана</strong>\
  \ (<strong>Масембая</strong>).</p>\r\n<p><strong>Кыз</strong> (баш.,тат.) &mdash;\
  \ девушка, девочка. <strong>Таш</strong> (баш.) &mdash; камень. <strong>Кызларташ</strong>\
  \ &mdash; девичий праздник, камень девушек, место проведения девичников &mdash;\
  \ весенних праздников и игр.\r\n"
name: Масим
name_alt: Кызлар-Таш
