coordinates:
- 54.158416
- 58.030278
description: "\r\n"
height: 1125
images: []
interpretation: "<b>Кусеу</b> (баш.) &mdash; кочевать, переходить с места на место.\
  \ <b>Имат</b> &mdash; башкирское имя. <b>Таш</b> (баш.)-камень. <b>Тау</b> (баш.)\
  \ &mdash; гора.\r\n"
name: Кусейматаш
name_alt: Кусейматау
