coordinates:
- 54.324398
- 58.525457
description: ''
height: 1032
images:
- comment: Вершина
  image: 3db57271ae6165fde8709a019fdc0ca0a95e3992.jpeg
- comment: Вышка
  image: 9d4e61a64b63b0d9159b54ac385e1bfe1c5de7aa.jpeg
interpretation: null
name: Репная
name_alt: null
