coordinates:
- 54.724536
- 58.923222
description: Скальные башни
height: 1267
images:
- comment: Вершина
  image: 916c678db4e4833afab68c49d3a72de3c4cf2dc8.jpeg
interpretation: null
name: null
name_alt: null
