coordinates:
- 53.807078
- 58.13364
description: null
height: 1009
images:
- comment: Вершина (вид с 1008)
  filename: a89ce604745733914cf0847fdeb715f89cb9abd1.jpeg
interpretation: null
name: null
name_alt: null
